# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: id_sam
instance_flavor: uom.mse.1c4g

# Volume
volumes:
  - vol_name: sam-v1
    vol_size: 5
  - vol_name: sam-v2
    vol_size: 5
  - vol_name: sam-v4
    vol_size: 5

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: sam-i1
    volumes: ['sam-v1', 'sam-v2', 'sam-v4']


