---
###################################################
#  University of Melbourne                        #
#  COMP90024 Cluster and Cloud Computing          #
#  2022 Semester 1 - Assignment 2                 #
#                                                 #
#  Team 58:                                       #
#  - (Sam)     Bin Zhang     895427  @ Melbourne  #
#  - (Joe)     Tianhuan Lu   894310  @ Melbourne  #
#  - (Leo)     Yicong Li    1307323  @ Melbourne  #
#  - (Peter)   Weiran Zou   1309198  @ Melbourne  #
#  - (Thomas)  Chenhao Gu   1147534  @ Melbourne  #
###################################################

couchdb_version: 3.2.2
couchdb_user: admin
couchdb_password: admin
couchdb_secret: secret
couchdb_erlang_cookie: a192aeb9904e6590849337933b000c99