---
# Configure local host and create instances on MRC
- hosts: localhost
  become: true
  vars_files:
    - host_vars/openstack.yaml
  roles:
    - role: localhost-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    - role: openstack-host-group

# Configure MRC instances
- hosts: all
  vars_files:
    - host_vars/mrc.yaml
  roles:
    - role: mrc-common
    - role: mrc-volumes
    - role: mrc-docker

# Create CouchDB container and set up CouchDB cluster
- name: Create CouchDB container and set up CouchDB cluster
  import_playbook: pb-couchdb.yaml

# Set up Docker Swarm
- name: Set up Docker Swarm
  import_playbook: pb-swarm.yaml

# Deploy back & front end and Twitter harvester as Docker Swarm Service
- name: swarm_leader
  become: true
  vars_files:
    - host_vars/mrc.yaml
  roles:
    - role: service-back-end
    - role: service-front-end
    - role: service-harvester


