---
# Create CouchDB container
- hosts: couchdb_coordinator, couchdb_node
  vars_files:
    - host_vars/mrc.yaml
    - host_vars/couchdb.yaml
  roles:
    - role: couchdb-setup

# Set up CouchDB cluster
- hosts: couchdb_node
  vars_files:
    - host_vars/mrc.yaml
    - host_vars/couchdb.yaml
  vars:
    coordinator: "{{ groups['couchdb_coordinator'][0] }}"
  roles:
    - role: couchdb-cluster