---
###################################################
#  University of Melbourne                        #
#  COMP90024 Cluster and Cloud Computing          #
#  2022 Semester 1 - Assignment 2                 #
#                                                 #
#  Team 58:                                       #
#  - (Sam)     Bin Zhang     895427  @ Melbourne  #
#  - (Joe)     Tianhuan Lu   894310  @ Melbourne  #
#  - (Leo)     Yicong Li    1307323  @ Melbourne  #
#  - (Peter)   Weiran Zou   1309198  @ Melbourne  #
#  - (Thomas)  Chenhao Gu   1147534  @ Melbourne  #
###################################################

- name: deploy server (back-end)
  become: true
  community.docker.docker_swarm_service:
    name: server
    image: leo727268082/server
    replicas: 2
    publish:
      - mode: ingress
        published_port: 5000
        target_port: 5000
    env:
      DB_SERVER: http://{{couchdb_user}}:{{couchdb_password}}@{{dest}}:5984