# Common vars
availability_zone: melbourne-qh2-uom
instance_image: aaddbad8-87d7-4ed7-9382-409b9bc42ca6
instance_key_name: demo-joe
instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: vol-1-1
    vol_size: 50
  - vol_name: vol-1-2
    vol_size: 10
  - vol_name: vol-2-1
    vol_size: 50
  - vol_name: vol-2-2
    vol_size: 10
  - vol_name: vol-3-1
    vol_size: 50
  - vol_name: vol-3-2
    vol_size: 10

# Security group
security_groups:
  - name: sg-admin
    description: "Security group to allow for SSH, HTTP or front end access"
  - name: sg-couch-db
    description: "Security group for communication between CouchDB nodes in cluster"
  - name: sg-docker-swarm
    description: "Security group for docker swarm"

security_group_rules_public:
  - name: sg-admin
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: sg-admin
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: sg-admin
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: sg-admin
    protocol: tcp
    port_range_min: 10000
    port_range_max: 10000
    remote_ip_prefix: 0.0.0.0/0

  # security groups for CoucheDB 
security_group_rules_private: 
  - name: sg-couch-db
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_group: sg-couch-db
  - name: sg-couch-db
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_group: sg-couch-db
  - name: sg-couch-db
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_group: sg-couch-db
  # docker swarm 
  - name: sg-docker-swarm
    protocol: tcp
    port_range_min: 2377
    port_range_max: 2377
    remote_group: sg-docker-swarm
  - name: sg-docker-swarm
    protocol: tcp
    port_range_min: 7496
    port_range_max: 7496
    remote_group: sg-docker-swarm
  - name: sg-docker-swarm
    protocol: udp
    port_range_min: 7496
    port_range_max: 7496
    remote_group: sg-docker-swarm
  - name: sg-docker-swarm
    protocol: udp
    port_range_min: 4789
    port_range_max: 4789
    remote_group: sg-docker-swarm


# Instance
instances:
  - name: server-1
    volumes: ['vol-1-1', 'vol-1-2']
  - name: server-2
    volumes: ['vol-2-1', 'vol-2-2']
  - name: server-3
    volumes: ['vol-3-1', 'vol-3-2']


